### ISSUE TITLE
LUA error

### ISSUE THREAD

**Issue by antarek** [michaelnpsp/KiwiPlates#3]
KiwiPlates version: 1.1.5

Issue:
When playing i get this LUA error using KiwiPlates:

> Message: integer overflow attempting to store -nan(ind)
> Time: Wed Dec  7 14:58:58 2022
> Count: 1
> Stack: integer overflow attempting to store -nan(ind)
> [string "=[C]"]: ?
> [string "@Interface/AddOns/KiwiPlates/modules/healthtext.lua"]:45: in function `?'
> [string "@Interface/AddOns/KiwiPlates/core.lua"]:320: in function `UpdatePlateValues'
> [string "@Interface/AddOns/KiwiPlates/core.lua"]:462: in function <Interface/AddOns/KiwiPlates/core.lua:400>
> [string "@Interface/AddOns/KiwiPlates/core.lua"]:739: in function `c'
> [string "@Interface/AddOns/KiwiPlates/init.lua"]:76: in function <Interface/AddOns/KiwiPlates/init.lua:76>
> 
> Locals: (*temporary) = "%d"
> (*temporary) = Infinite

**Comment by michaelnpsp** [comment]
I cannot replicate some issues, can you send me your profile configuration ? You can export the profile to text format going to Profiles/Export Profile button.
