### ISSUE TITLE
nameplates are very small on high resolution monitors

### ISSUE THREAD

**Issue by blacha** [michaelnpsp/KiwiPlates#7]
Using Kiwiplates on high resolution monitors, the nameplates are very very small.

I worked around the issue by doubling the `pixelScale` here https://github.com/michaelnpsp/KiwiPlates/blob/main/core.lua#L1094

I am not sure what the best fix would be, possibly if the resolution is >= 3180x2140 then double the `pixelScale`? 

ToxUI has similar logic but uses a hard coded list of resolutions, which doesn't work for me as my resolution is non standard :(

```lua
local doubleScaleResolutions = {
  [2054] = true,
  [2160] = true,
  [2880] = true,
}

function F.PixelPerfect()
  local perfectScale = 768 / E.physicalHeight
  if doubleScaleResolutions[E.physicalHeight] then perfectScale = perfectScale * 2 end
  return perfectScale
end
```

**Comment by michaelnpsp** [comment]
I can add a slider in general options to change the scale.
Another posibility: What about simply going to the skins tab and increase the font sizes and the width and height of the health bar, cast bar, etc ?

**Comment by blacha** [comment]
Awesome work! I just tried out the new nameplate scaling, it works great and fixes my problem!

I did start going through changing all the settings (font size, width, etc..)  one by one but there are a lot of places to change.
